---
output:
  reprex::reprex_document:
    venue: "gh"
    advertise: FALSE
    session_info: TRUE
    style: TRUE
    comment: "#;-)"
    tidyverse_quiet: FALSE
    std_out_err: TRUE
knit: reprex::reprex_render
---
Define and write the Benford's distribution
```{r}  
benford <- function(d) {
  log10(1 + 1/d)
}
```

Define and write the uniform distribution that is (t-1)/9 for 1<t<10
```{r}  
uniform <- (1:9 ) / 9
```

Define and write the unit exponential distribution 1-exp(-t)
```{r}  
exponential <- function(d) {
  1 - exp(-d)
}
```

Log-normal distribution
```{r}  
log_normal <- function(d) {
  dnorm(log(d), mean = 1, sd = 1)
}
```


I want to compare different common probabilities distribution to see if there is one that is near to the Benford's diostribution
```{r}  
leading_digit <- 1:9
 

prob_dist <- data.frame(
  "Leading digit" = leading_digit,
  "Benford's law" = benford(1:9),
  "Uniform (1,10)" = uniform,
  "Exponential (1,10)" = exponential(1:9),
  "log-normal (1,10)" = log_normal(1:9)
)

print(prob_dist)

```
